"""
MODULES:

- BASICALLY LIKE A CODE LIBRARY
- MODULE IS A FILE WRITTEN BY ANOTHER PROGRAMMER THAT GENERALLY HAS A FUNCTION(S)
  WE CAN USE
- IN SHORT TO BORROW A FILE, WE USE MODULES
- SYNTAX :-
    IMPORT FILE_NAME
    COMMAND

- OS (OPERATING SYSTEM) IS A BUILT IT FILE IN PYTHON
- OS.REMOVE("FILE_NAME") IS ALSO A BUILT IN FUNCTION THAT DELETES FILES
   
"""

# Q. IMPORT AND REMOVE SAMPLE.TXT
import os
os.remove("Sample.txt")
