"""
- PYHTON CAN BE USED TO PERFORM OPERATIONS ON A FILE (READ/WRITE)
- TYPES OF FILES :-
    1). TEXT FILES (CHARACTERS) : .TXT , .DOCX , .LOG ETC
    2). BINARY FILES (NON-CHARACTERS): .MP4 , .MOV , .PNG , .JPEG

- OPEN, READ AND CLOSE FILE :-
- WE HAVE TO OPEN FILE TO READ OR WRITE ON IT
- HOW TO OPEN AND CLOSE : 
    F = OPEN("FILE_NAME","MODE")
    FILE_NAME CAN BE ABC.TXT , DEF.DOCX
    MODE CAN BE R(READ) AND W(WRITE)
    IF YOU DONT WRITE ANY MODE, IT IS TAKEN AS R
    TO CLOSE FILE = F.CLOSE()

- READ METHOD:-
    1). DATA = F.READ()         # READ WHOLE 
    2). DATA = F.READ(N)        # READ N CHARACTERS AT A TIME
    2). DATA = F.READLINE()     # READS 1 LINE AT A TIME

    

"""
print("\n")


# Q1. OPEN AND READ FIRST 2 LINES "DATATYPES" FILE FROM BASIC CONCEPTS FOLDER
f = open("Demo.txt","r")
line1 = f.readline()
print(line1)
line2 = f.readline()
print(line2)
f.close()

